##
##
## ============================================================================
## WYSHCARE PLATFORM
## ============================================================================
##
## File: infra/k8s/overlays/staging/kustomization.yaml
##
## Product:
## WyshCare Healthcare Operating System
##
## Brand:
## WYSH
##
## Founder:
## Vimarshak Prudhvi
##
## Purpose:
## Configuration file for staging
##
## Responsibilities:
##  * - Support infrastructure functionality
##
## Last Reviewed:
## 2026-06-12
##
## ============================================================================
## (c) Wysh Technologies
## Built by Vimarshak Prudhvi
## All Rights Reserved
## ============================================================================
##

resources:
  - ../../base/namespace.yaml
  - ../../base/backend-deployment.yaml
  - ../../base/frontend-deployment.yaml
  - ../../base/services.yaml
  - ../../base/ingress.yaml
